version: "3.8"

services:
  almachi:
    image: ghcr.io/${GH_OWNER:-leonardo22f}/almachi:${IMAGE_VERSION:-1.0.6}
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.almachi.entrypoints=http"
        - "traefik.http.routers.almachi.rule=Host(`almachi.byronrm.com`)"
        - "traefik.http.middlewares.almachi-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.almachi.middlewares=almachi-https-redirect"
        - "traefik.http.routers.almachi-secure.entrypoints=https"
        - "traefik.http.routers.almachi-secure.rule=Host(`almachi.byronrm.com`)"
        - "traefik.http.routers.almachi-secure.tls=true"
        - "traefik.http.routers.almachi-secure.tls.certresolver=http"
        - "traefik.http.routers.almachi-secure.service=almachi"
        - "traefik.http.services.almachi.loadbalancer.server.port=5000"
        - "traefik.docker.network=traefik-public"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
